Revert "Floss: enable BLE build"
This reverts commit c07237d04712cbe7c05cc27e5cea097faef5572b.

Reason: Otherwise build fails with
FileNotFoundError: [Errno 2] No such file or directory: b'/var/tmp/portage/net-wireless/floss_tools-0.0.1-r3028/work/build/out/Default/gen/bt/system/bta/audio_set_configurations.bfbs'
 * ERROR: net-wireless/floss_tools-0.0.1-r3028::chromiumos failed (install phase):
 *   doins failed
Change-Id: I7121eba5d747d79e0b43ec4ceebc3ec77b01c83d